insert into users(username, name, surname, city, phone, email, password, about, credits_balance) values ("Ivan923", "Ivan", "Movchanets", "Klaipeda1", "+111111111111", "admin@admin.com", "$2a$12$BHFe7BAUeh.jFmMS.FUmou15rR4wCuD74rHGNTOAuO0JAcIgu56Ra", "I am first user", 0.00);
insert into users(username, name, surname, city, phone, email, password, about, credits_balance) values ("Vitalij123", "Vitalij", "Ivaniuk", "Klaipeda2", "+222222222222", "user@user.com", "$2a$12$dXr9wY596x1LfySTnmkopO5eGUCFOIoWTCaiHmkXFH5HebM6bKDcK", "I am second user user", 150.00);
insert into users(username, name, surname, city, phone, email, password, about, credits_balance) values ("Petras347", "Petras", "Kurmelis", "Klaipeda3", "+333333333333", "user2@user2.com", "$2a$12$dXr9wY596x1LfySTnmkopO5eGUCFOIoWTCaiHmkXFH5HebM6bKDcK", "I am third user user", 0.00);

insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "18:00", "180", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", "11.99","0.00", 11);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("LESSON", 0,  "lessonsGroup1", "Lesson1", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "16:00", "100", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", "20.99", "0.00", 20);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "Meditation in Nida", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "60", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", "120.00", "0.00", 10);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "Yoga Nidra", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "18:00", "100", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "31.99", "31.99", "0.00", 11);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("LESSON", 0,  "lessonsGroup1", "nesamoniu pratimai", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "16:00", "340", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "41.99", "41.99", "00.00", 20);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "40", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "50.00", "50.00", "0.00", 10);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "event3", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "18:00", "40", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "75.99", "75.99", "0.00", 11);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("LESSON", 0,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "10", "16:00", "50", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "85.99", "85.99", "0.00", 20);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "Bom bom yoga", "OTHER", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "162", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "150.00", "150.00", "0.00", 10);

insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "18:00", "180", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "45.90", "45.90", "0.00", 11);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 1,  "Event", "Fly Yoga EXCLUSIVE", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "16:00", "200", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "245.90", "245.90", "0.00", 20);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "400", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", "120.00", "0.00", 10);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "18:00", "100", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "31.99", "31.99", "0.00", 11);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "16:00", "340", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "21.99", "21.99", "00.00", 20);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "40", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "30.00", "30.00", "0.00", 10);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "1", "18:00", "40", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", "11.99", "0.00", 11);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-28", "10", "16:00", "50", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", "20.99", "0.00", 20);
insert into events(type, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, duration_days, start_time, duration_minutes, text_about, image_src, common_price, final_price, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "162", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", "120.00", "0.00", 10);

insert into events_days(event_id, day_of_week) values(2, "WEDNESDAY");
insert into events_days(event_id, day_of_week) values(2, "FRIDAY");
insert into events_days(event_id, day_of_week) values(2, "SUNDAY");
insert into events_days(event_id, day_of_week) values (1, "SUNDAY")
insert into events_days(event_id, day_of_week) values (1, "SATURDAY")
insert into events_days(event_id, day_of_week) values(3, "WEDNESDAY");
insert into events_days(event_id, day_of_week) values(3, "FRIDAY");


insert into users_roles (user_id, role) values (1, "USER");
insert into users_roles (user_id, role) values (1, "ADMIN");
insert into users_roles (user_id, role) values (2, "USER");
insert into users_roles (user_id, role) values (3, "USER");


