insert into users(user_name, name, surname, city, phone, email, about) values ("Errid1", "Ivan1", "Movchanets1", "Klaipeda1", "+111111111111", "georgeridan1@gmail.com", "I am first user");
insert into users(user_name, name, surname, city, phone, email, about) values ("Errid2", "Ivan2", "Movchanets2", "Klaipeda2", "+222222222222", "georgeridan3@gmail.com", "I am second user user");
insert into users(user_name, name, surname, city, phone, email, about) values ("Errid3", "Ivan3", "Movchanets3", "Klaipeda3", "+333333333333", "georgeridan3@gmail.com", "I am third user user");
insert into users(user_name, name, surname, city, phone, email, about) values ("Errid4", "Ivan4", "Movchanets4", "Klaipeda4", "+444444444444", "georgeridan4@gmail.com", "I am fourth user user");

insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-04-28", "1", "18:00", "2", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", 1, "10.00", 11);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-05-28", "10", "16:00", "2", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", 1, "10.00", 20);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "8", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", 1, "10.00", 10);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-04-28", "1", "18:00", "2", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", 1, "10.00", 11);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-05-28", "10", "16:00", "2", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", 1, "10.00", 20);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "8", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", 1, "10.00", 10);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-04-28", "1", "18:00", "2", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", 1, "10.00", 11);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-05-28", "10", "16:00", "2", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", 1, "10.00", 20);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "8", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", 1, "10.00", 10);

insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-04-28", "1", "18:00", "2", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", 1, "10.00", 11);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-05-28", "10", "16:00", "2", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", 1, "10.00", 20);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "8", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", 1, "10.00", 10);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-04-28", "1", "18:00", "2", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", 1, "10.00", 11);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-05-28", "10", "16:00", "2", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", 1, "10.00", 20);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "8", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", 1, "10.00", 10);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "event1", "NIDRA", "Klaipeda", "Nesamoniu str. 11-8 (2nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-04-28", "1", "18:00", "2", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "11.99", 1, "10.00", 11);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("LESSON", 1,  "lessonsGroup1", "Lesson for all", "ACTIVE", "Kaunas", "Nesamoniu str. 12-91 (3nd floor)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-05-28", "10", "16:00", "2", "This is text about this lesson varryyyyy loooooong teeeeext", "/images/image.jpg", "20.99", 1, "10.00", 20);
insert into events(type_of, is_repeatable, group_id, title, theme, city, address, url_google_maps,  start_date, period_days, start_time, duration_hours, text_about, image_src, common_price, is_discount, discount, vacancies_limit) values ("EVENT", 0,  "single", "MEDITATATION IN NIDA", "MEDITATION", "Klaipeda", "Nida, Nesamoniu str. 2 (Enter from back side)","https://goo.gl/maps/ezCxf4tMarLiwVPW9", "2022-06-21", "1", "06:00", "8", "This is text about event varryyyyy loooooong teeeeext", "/images/image.jpg", "120.00", 1, "10.00", 10);


insert into events_users(event_id, user_id) values(1, 1);
insert into events_users(event_id, user_id) values(1, 2);
insert into events_users(event_id, user_id) values(1, 3);
insert into events_users(event_id, user_id) values(1, 4);
insert into events_users(event_id, user_id) values(2, 3);
insert into events_users(event_id, user_id) values(2, 4);
insert into events_users(event_id, user_id) values(3, 1);
insert into events_users(event_id, user_id) values(3, 4);

            --no need to add in this table days of week for single events
insert into event_days_of_week(event_id, day_of_week) values(2, "WEDNESDAY");
insert into event_days_of_week(event_id, day_of_week) values(2, "FRIDAY");
insert into event_days_of_week(event_id, day_of_week) values(2, "SUNDAY");
insert into event_days_of_week(event_id, day_of_week) values (1, "SUNDAY")
insert into event_days_of_week(event_id, day_of_week) values (1, "SATURDAY")
insert into event_days_of_week(event_id, day_of_week) values(3, "WEDNESDAY");
insert into event_days_of_week(event_id, day_of_week) values(3, "FRIDAY");


--user 1 press
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 0, "2022-05-01 19:32:23", 0.00, 0.00, 1, 2);
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 0, "2022-05-01 19:34:43", 0.00, 0.00, 1, 3);
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 1, "2022-05-01 20:12:13", 10.00, 0.00, 1, 2);
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 1, "2022-05-01 20:12:23", 10.00, 0.00, 1, 3);
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 1, "2022-05-01 20:12:13", 10.00, 0.00, 1, 2);
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 1, "2022-05-01 20:12:23", 0.00, 10.00, 3, 1);
--user pressed +
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 0, "2022-05-01 19:32:23", 0.00, 0.00, 2, 1);
 --admin pressed + about payment
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 1, "2022-05-01 21:32:23", 10.00, 0.00, 2, 1);
--return money to user or he want to reserve another event (using subscribes and credits)
insert into payments (type, method, is_paid, time_stamp, sum, credits, user_id, event_id) values ("INCOME", "FRIEND", 0, "2022-05-01 22:32:23", 0.00, 0.00, 2, 1);

insert into users_roles (user_id, role) values (1, "USER");
insert into users_roles (user_id, role) values (1, "ADMIN");
insert into users_roles (user_id, role) values (2, "USER");
insert into users_roles (user_id, role) values (3, "USER");
insert into users_roles (user_id, role) values (4, "USER");

